### ISSUE TITLE
Binary sensor not getting updated

### ISSUE THREAD

**Issue by backslashV** [NickM-27/swatch-hass-integration#4]
Hi,
I'm not quite sure how the binary sensor gets updated. I'm sending the detect request using Postman on Windows and get the result there, but the binary sensor doesn't reflect the result.

Also, when I run the service like so I don't see the binary sensor getting updated:
```
service: swatch.detect_object
data:
  image_url: <img url>
target:
 entity_id:
```

Any help is appreciated.

**Comment by NickM-27** [comment]
Currently the sensor only updates when it runs directly through HASS. Not sure why that wouldn't be working correctly if it is seeing things. 

I'm planning an update soon that will keep the state so the sensor will update if it is called externally

**Comment by backslashV** [comment]
> Currently the sensor only updates when it runs directly through HASS. Not sure why that wouldn't be working correctly if it is seeing things. 
> 
> I'm planning an update soon that will keep the state so the sensor will update if it is called externally

Thanks. So, with above service call it's supposed to update the entity? Note that I haven't provided anything for the entity as that will result in an "unknown" error.

**Comment by NickM-27** [comment]
The entity needs to be provided in the format binary_sensor.whatever_it_is

**Comment by backslashV** [comment]
> The entity needs to be provided in the format binary_sensor.whatever_it_is

Providing the swatch entity results in the error below:

```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/swatch/api.py:58
Integration: Swatch (documentation, issues)
First occurred: May 7, 2022, 11:54:59 PM (10 occurrences)
Last logged: 11:47:41 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: str() argument 2 must be str, not dict
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/swatch/binary_sensor.py", line 126, in detect_object
    resp = await self._api.async_detect_camera(self._cam_name, image_url)
  File "/config/custom_components/swatch/api.py", line 58, in async_detect_camera
    str(
TypeError: str() argument 2 must be str, not dict
```

**Comment by NickM-27** [comment]
I see, the error you are seeing will be fixed in #5 and then fully addressed in #6

**Comment by backslashV** [comment]
Just a quick clarification, with the new config model, I have the following variants:
```
midday:
  color_lower: 136, 32, 41
  color_upper: 166, 40, 51
night_lights_on:
  color_lower: 58, 20, 23
  color_upper: 70, 24, 29
night_spotlight:
  color_lower: 109, 58, 71
  color_upper: 133, 70, 87
```
When I run color test on a white picture (cropped from the original image), I get
```
{
    "message": "The dominant color is (252, 252, 252) with a mixed palette as [(252, 252, 252), (252, 244, 252), (256, 252, 252), (256, 252, 252)]",
    "success": true
}
```
and then detect on the original (uncropped) picture, it still says
```
{
    "door": {
        "stop_sign": {
            "area": 24,
            "result": true,
            "variant": "night_spotlight"
        }
    }
}
```
The color values are obviously out of the range for night_spotlight. Why is it still detecting the object there?

**Comment by NickM-27** [comment]
> Just a quick clarification, with the new config model, I have the following variants:
> 
> ```
> 
> midday:
> 
>   color_lower: 136, 32, 41
> 
>   color_upper: 166, 40, 51
> 
> night_lights_on:
> 
>   color_lower: 58, 20, 23
> 
>   color_upper: 70, 24, 29
> 
> night_spotlight:
> 
>   color_lower: 109, 58, 71
> 
>   color_upper: 133, 70, 87
> 
> ```
> 
> When I run color test on a white picture (cropped from the original image), I get
> 
> ```
> 
> {
> 
>     "message": "The dominant color is (252, 252, 252) with a mixed palette as [(252, 252, 252), (252, 244, 252), (256, 252, 252), (256, 252, 252)]",
> 
>     "success": true
> 
> }
> 
> ```
> 
> and then detect on the original (uncropped) picture, it still says
> 
> ```
> 
> {
> 
>     "door": {
> 
>         "stop_sign": {
> 
>             "area": 24,
> 
>             "result": true,
> 
>             "variant": "night_spotlight"
> 
>         }
> 
>     }
> 
> }
> 
> ```
> 
> The color values are obviously out of the range for night_spotlight. Why is it still detecting the object there?

What is your min_area ? That's what defines if it's a positive result or not

**Comment by backslashV** [comment]
min_area: 5
    max_area: 80

If I raise the min_area, it's gonna miss some other legit objects. So, how do lower and upper color values play a role here?

**Comment by NickM-27** [comment]
There are some misconceptions that I should make more clear in the docs. 

> If I raise the min_area, it's gonna miss some other legit objects.

So you can see from the `detect` payload that it found 24 pixels within the range which is > 5 so it is a true match. Both 5 and 80 seem quite low but that depends on the resolution of the camera / area of the zone. For example the trash can images I have in the README, the trash can is usually 1000 to 1200 pixels. min_area of 5 is very little range between good value and a couple stray pixels that happen to fall into the range. I think this is a case where tuning the color values would make it work so the min_area can be higher. I do recognize that currently it is not easy.

Also, the color test is more of a "starting point" to get ideas for values to use as lower and upper, but it isn't meant to test or validate the values that are there.

> So, how do lower and upper color values play a role here?

So the way this works is it essentially considers the `R`,`G`,`B` values of each pixel and compares them with the lower and upper. 

So for example if there is a pixel with R: 140, G: 38, B: 55 and we are considering your midday variant:
```yaml
midday:
  color_lower: 136, 32, 41
  color_upper: 166, 40, 51
```

it will check: 
R: 136 < 140 < 166 ✅  
G: 32 < 38 < 40 ✅ 
B: 41 < 55 < 51 ❌ 

so that pixel will be ignored. Once all the pixels are tested it counts how many were fully within the lower and upper ranges. 

I think a good way to start with this will be to add docs for getting started with a new object. But in general, I recommend using the color test to get a rough value, make the lower values 90% of the original and the upper values 100% of the original. Then run detect and see if the object is there and adjust accordingly.
